database:
  url: jdbc:mysql://localhost:3306/certificates?autoReconnect=true
  password: root
  username: root
  driverClass: com.mysql.jdbc.Driver
  properties:
   hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   hibernate.format_sql: true
   hibernate.hbm2ddl.auto: update
   hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
   hibernate.connection.provider_class: org.hibernate.connection.C3P0ConnectionProvider
   hibernate.c3p0.acquire_increment: 5
   hibernate.c3p0.min_size: 10
   hibernate.c3p0.max_size: 50
   hibernate.c3p0.timeout: 300
   hibernate.c3p0.max_statements: 500
   hibernate.c3p0.idle_test_period: 30

http:
  port: 8080
  adminPort: 8081